name: IITM Action Validation

on:
  workflow_dispatch: # Allows manual triggering to ensure it is the most recent run

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2009286@ds.study.iitm.ac.in
        run: echo "Execution verified."
